org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=NadienDev
modid=ae2usefulutilities
mod_named=AE2 Useful Utilities
mod_name=AE2_Useful_Utilities
description=Quality-of-life additions for Applied Energistics 2. Enhances wireless terminals with extra functionality. Curios support included. Optional chunk loading for Infinity/Dimensional Card users.
license=All Rights Reserved
mod_group_id=nadiendev.ae2usefulutilities
mod_version=1.1.1
tag_lanzador=NeoForge

# Minecraft and NeoForge versions
mcversion=1.21.1
neoversion=21.1.215
loader_version=[4,)

# NeoForge Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false


# Dependencies 
jei_version=19.27.0.340
ae2_version=19.2.17
guideme_version=21.1.15
ae2wtlib_version=19.5.0
curios_version=9.5.1+1.21.1
aeib_version=7402808


