org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

author=NadienDev
modid=ae2usefulutilities
mod_named=AE2 Useful Utilities
mod_name=AE2_Useful_Utilities
description=Quality-of-life additions for Applied Energistics 2. Enhances wireless terminals with extra functionality. Curios support included. Optional chunk loading for Infinity/Dimensional Card users.
license=All Rights Reserved
mod_group_id=nadiendev.ae2usefulutilities
mod_version=2.0.2
tag_lanzador=NeoForge

# Minecraft and NeoForge versions
mcversion=26.1.2
mcversion_range=[26.1.2]
neoversion=26.1.2.78
loader_version=[4,)

# Dependencies
ae2_version=26.1.10-beta
guideme_version=26.1.12-beta
curios_version=15.0.0+26.1.2
aeib_version_id=8132173